/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewTeamImport } from './routes/new-team'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NewTeamRoute = NewTeamImport.update({
  id: '/new-team',
  path: '/new-team',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/new-team': {
      id: '/new-team'
      path: '/new-team'
      fullPath: '/new-team'
      preLoaderRoute: typeof NewTeamImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-team': typeof NewTeamRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-team': typeof NewTeamRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/new-team': typeof NewTeamRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-team'
  id: '__root__' | '/' | '/new-team'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewTeamRoute: typeof NewTeamRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewTeamRoute: NewTeamRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/new-team"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/new-team": {
      "filePath": "new-team.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
